version: "3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: es
    environment:
      - discovery.type=single-node
    # ports:
    #   - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  backend:
    build: ./flask-app
    depends_on:
      - es
  nginx:
    build: .
    container_name: nginx
    ports:
      - "8080:80"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
    esdata1:
      driver: local
    



# version: '3.3'
# services:
#   backend:
#       build: ./flask-app
#       depends_on:
#         - es
#       expose:
#         - "5000"
#       networks:
#         - elastic
#   es: 
#       image: elasticsearch:6.8.18
#       container_name: es
#       environment:
#         - node.name=es
#         - cluster.name=es
#         - bootstrap.memory_lock=true
#         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#         - transport.host=localhost
#         - boostrap.system_call_filter=false
#       ulimits:
#         memlock:
#           soft: -1
#           hard: -1
#       volumes:
#         - ./data:/usr/share/elasticsearch/data
#       ports:
#         - 9200:9200
#       networks:
#         - elastic
# networks:
#   elastic:
# volumes:
#   data:
